#!/bin/sh
#
# Munin plugin for measuring the core temperature of the BCM2835 SoC on a
# Raspberry Pi.
#
# Add the following lines to /etc/munin/plugin-conf.d/raspi_temp:
#
# [raspi_temp]
# user root
#
case $1 in
    config)
        cat <<'EOM'
graph_title BCM2835 core temperature
graph_vlabel temp in C
graph_args --base 1000 -l 0
graph_category Temperature
temp.label Temperature
temp.warning 60
temp.critical 85
EOM
        exit 0;;
esac

echo "temp.value `/opt/vc/bin/vcgencmd measure_temp | sed -n "s/temp=\(.*\)'C/\1/p"`"
